name: deploy
on: [push]
jobs:
  deploy:
    name: Deploy Dist
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Deploy Via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: dist/*
          target: benjaminhinchliff/public/
        
